const ADD_RECIPE = 'ADD_RECIPE';
const ADD_INGREDIENT = 'ADD_INGREDIENT';
const SET_RECIPES = 'SET_RECIPES';
const FETCH_RECIPES = 'FETCH_RECIPES';

export { ADD_RECIPE, ADD_INGREDIENT, SET_RECIPES, FETCH_RECIPES };
